#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TEST")]
public partial class StaffdbDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Определения метода расширяемости
  partial void OnCreated();
  partial void InsertStaff(Staff instance);
  partial void UpdateStaff(Staff instance);
  partial void DeleteStaff(Staff instance);
  #endregion
	
	public StaffdbDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TESTConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public StaffdbDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StaffdbDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StaffdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StaffdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Staff> Staff
	{
		get
		{
			return this.GetTable<Staff>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Staff")]
public partial class Staff : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdStaff;
	
	private int _IdClinic;
	
	private string _Sername;
	
	private string _Name;
	
	private string _MiddleName;
	
	private string _Position;
	
	private string _TelNumber;
	
	private string _PCNumber;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdStaffChanging(int value);
    partial void OnIdStaffChanged();
    partial void OnIdClinicChanging(int value);
    partial void OnIdClinicChanged();
    partial void OnSernameChanging(string value);
    partial void OnSernameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnTelNumberChanging(string value);
    partial void OnTelNumberChanged();
    partial void OnPCNumberChanging(string value);
    partial void OnPCNumberChanged();
    #endregion
	
	public Staff()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStaff", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdStaff
	{
		get
		{
			return this._IdStaff;
		}
		set
		{
			if ((this._IdStaff != value))
			{
				this.OnIdStaffChanging(value);
				this.SendPropertyChanging();
				this._IdStaff = value;
				this.SendPropertyChanged("IdStaff");
				this.OnIdStaffChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClinic", DbType="Int NOT NULL")]
	public int IdClinic
	{
		get
		{
			return this._IdClinic;
		}
		set
		{
			if ((this._IdClinic != value))
			{
				this.OnIdClinicChanging(value);
				this.SendPropertyChanging();
				this._IdClinic = value;
				this.SendPropertyChanged("IdClinic");
				this.OnIdClinicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Sername
	{
		get
		{
			return this._Sername;
		}
		set
		{
			if ((this._Sername != value))
			{
				this.OnSernameChanging(value);
				this.SendPropertyChanging();
				this._Sername = value;
				this.SendPropertyChanged("Sername");
				this.OnSernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this.OnMiddleNameChanging(value);
				this.SendPropertyChanging();
				this._MiddleName = value;
				this.SendPropertyChanged("MiddleName");
				this.OnMiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Position
	{
		get
		{
			return this._Position;
		}
		set
		{
			if ((this._Position != value))
			{
				this.OnPositionChanging(value);
				this.SendPropertyChanging();
				this._Position = value;
				this.SendPropertyChanged("Position");
				this.OnPositionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TelNumber
	{
		get
		{
			return this._TelNumber;
		}
		set
		{
			if ((this._TelNumber != value))
			{
				this.OnTelNumberChanging(value);
				this.SendPropertyChanging();
				this._TelNumber = value;
				this.SendPropertyChanged("TelNumber");
				this.OnTelNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string PCNumber
	{
		get
		{
			return this._PCNumber;
		}
		set
		{
			if ((this._PCNumber != value))
			{
				this.OnPCNumberChanging(value);
				this.SendPropertyChanging();
				this._PCNumber = value;
				this.SendPropertyChanged("PCNumber");
				this.OnPCNumberChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
